### ESP32 used is a MH-ET-LIVE, also known as Wemos D32 Mini 
### The modbus TTL to RS485 interface used is a XY-017  (RS3485). No flow control needed and 3.3V powersupply
esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

uart:
  id: mod_bus
  tx_pin: 23
  rx_pin: 19
  baud_rate: 19200
  stop_bits: 1
  parity: even