substitutions:
  en_external_humidity_sensor: "Humidity sensor (external)"
  en_temp_to_outside: "Temperature to outside"
  en_humidity_to_outside: "Humidity to outside"
  en_temp_from_outside: "Temperature from outside"
  en_supply_pressure: "Supply pressure"
  en_exhaust_pressure: "Exhaust pressure"
  en_setpoint_inlet_volume: "Setpoint inlet voulme"
  en_current_inlet_volume: "Current intake air Volume"
  en_setpoint_outlet_volume: "Setpoint exhaust air volume"
  en_current_outlet_volume: "Current exhaust air volume"
  en_frost_heater_power: "Frost heater power"
  en_frost_fan_reduction: "Frost fan reduction"
  en_current_filter_hours: "Current filter hours"
  en_current_filter_days: "Current filter days"
  en_exchange_filter_in: "Exchange filter in"
  en_huidig_filter_m3_h: "Filter m3/h"
  en_frost_status: "Frost status"
  en_bypass_boost_fan_stand: "Bypass Boost fan speed"
  en_vacation: "Vacation"
  en_speed: "Speed"
  en_auto: "Auto"
  en_open: "Open"
  en_closed: "Closed"
  en_ventilatie_stand: "Ventilation speed"
  en_brink_modbusflow_waarde: "Modbus flow step"

  lu_external_humidity_sensor: "Vochtsensor"
  lu_temp_to_outside: "Buiten uitblaas temperatuur"
  lu_humidity_to_outside: "Buiten uitblaas luchtvochtigheid"
  lu_temp_from_outside: "Buiten aanzuig temperatuur"
  lu_supply_pressure: "Druk inblaas"
  lu_exhaust_pressure: "Druk uitblaas"
  lu_setpoint_inlet_volume: "Inlaatluchtvolume ingesteld"
  lu_current_inlet_volume: "Uitlaatluchtvolume ingesteld"
  lu_setpoint_outlet_volume: Uitlaatluchtvolume ingesteld
  lu_current_outlet_volume: "Huidig uitlaatluchtvolume"
  lu_frost_heater_power: "Bevriezing heaterpower"
  lu_frost_fan_reduction: "Bevriezing fan reductie"
  lu_current_filter_hours: "Filter uren"
  lu_current_filter_days: "Filter dagen"
  lu_exchange_filter_in: "Filter wissel in"
  lu_huidig_filter_m3_h: "Filter m3/h"
  lu_frost_status: "Bevriezing status"
  lu_bypass_boost_fan_stand: "Bypass Boost fan stand"
  lu_vacation: "Vakantie"
  lu_speed: "Stand"
  lu_auto: "Auto"
  lu_open: "Open"
  lu_closed: "Dicht"
  lu_ventilatie_stand: "Ventilatie stand"
  lu_brink_modbusflow_waarde: "Modbus flow waarde"
