substitutions:
  en_temp_to_inside: Temperature to inside
  en_humidity_to_inside: Humidity to inside
  en_dewpoint_to_inside: Dewpoint to inside
  en_external_humidity_sensor: Humidity sensor (external)
  en_temp_to_outside: Temperature to outside
  en_humidity_to_outside: Humidity to outside
  en_temp_from_outside: Temperature from outside
  en_supply_pressure: Supply pressure
  en_exhaust_pressure: Exhaust pressure
  en_setpoint_inlet_volume: Setpoint inlet volume
  en_current_inlet_volume: Current intake air Volume
  en_setpoint_outlet_volume: Setpoint exhaust air volume
  en_current_outlet_volume: Current exhaust air volume
  en_frost_heater_power: Frost heater power
  en_frost_fan_reduction: Frost fan reduction
  en_current_filter_hours: Current filter hours
  en_current_filter_days: Current filter days
  en_exchange_filter_in: Exchange filter in
  en_huidig_filter_m3_h: Filter m3/h
  en_frost_status: Frost status
  en_bypass_boost_fan_stand: Bypass Boost fan speed
  en_vacation: Vacation
  en_speed: Speed
  en_auto: Auto
  en_open: Open
  en_closed: Closed
  en_ventilatie_stand: Ventilation speed
  en_brink_modbusflow_waarde: Modbus flow step
  en_status: Status
  en_rht_sensor: RHT sensor
  en_brink_imbalance_intake: Brink imbalance intake
  en_brink_bypass_from_dwelling: Bypass temp from home
  en_brink_bypass_from_outside: Bypass temp from outside
  en_brink_bypass_hysterese: Bypass hysteresis
  en_brink_frost_control_temperature: Freezing control temperature
  en_brink_frost_minimum_inlet_temperature: Freezing minimum inlet temperature
  en_brink_imbalance_exhaust: Fan Imbalance Exhaust
  en_brink_dagen_filter_wissel: Days filter change
  # SCD41 sensor
  en_co2_from_inside: CO2 from inside
  en_humidity_from_inside: Humidity from inside
  en_temp_from_inside: Temperature from inside

  nl_temp_to_inside: Binnen uitblaas temperatuur
  nl_humidity_to_inside: Binnen uitblaas luchtvochtigheid
  nl_dewpoint_to_inside: Binnen dauwpunt
  nl_external_humidity_sensor: Vochtsensor
  nl_temp_to_outside: Buiten uitblaas temperatuur
  nl_humidity_to_outside: Buiten uitblaas luchtvochtigheid
  nl_temp_from_outside: Buiten aanzuig temperatuur
  nl_supply_pressure: Druk inblaas
  nl_exhaust_pressure: Druk uitblaas
  nl_setpoint_inlet_volume: Inlaatluchtvolume ingesteld
  nl_current_inlet_volume: Uitlaatluchtvolume ingesteld
  nl_setpoint_outlet_volume: Uitlaatluchtvolume ingesteld
  nl_current_outlet_volume: Huidig uitlaatluchtvolume
  nl_frost_heater_power: Bevriezing heaterpower
  nl_frost_fan_reduction: Bevriezing fan reductie
  nl_current_filter_hours: Filter uren
  nl_current_filter_days: Filter dagen
  nl_exchange_filter_in: Filter wissel in
  nl_huidig_filter_m3_h: Filter m3/h
  nl_frost_status: Bevriezing status
  nl_bypass_boost_fan_stand: Bypass Boost fan stand
  nl_vacation: Vakantie
  nl_speed: Stand
  nl_auto: Auto
  nl_open: Open
  nl_closed: Dicht
  nl_ventilatie_stand: Ventilatie stand
  nl_brink_modbusflow_waarde: Modbus flow waarde
  nl_status: Status
  nl_rht_sensor: Vochtsensor
  nl_brink_imbalance_intake: Brink imbalance intake
  nl_brink_bypass_from_dwelling: Bypass temp uit woning
  nl_brink_bypass_from_outside: Bypass temp van buiten
  nl_brink_bypass_hysterese: bypass hysteresis
  nl_brink_frost_control_temperature: Bevriezing controle temperatuur
  nl_brink_frost_minimum_inlet_temperature: Bevriezing minimum inlaat temperatuur
  nl_brink_imbalance_exhaust: Fan Onbalans Uitlaat
  nl_brink_dagen_filter_wissel: Dagen filter wissel
  # SCD41 sensor
  nl_co2_from_inside: Binnen aanzuig CO2
  nl_humidity_from_inside: Binnen aanzuig luchtvochtigheid
  nl_temp_from_inside: Fan Onbalans Inlaat
