### ESP32S3 used is a LILYGO ESP32S3-T7
### The modbus TTL to RS485 interface used is a XY-017  (RS3485). No flow control needed and 3.3V powersupply
esp32:
  board: adafruit_feather_esp32s3_nopsram
  framework:
    type: arduino

esphome:
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

# Modbus uart
uart:
  tx_pin: 16
  rx_pin: 12

# Option for 2x I2C connectors  ***experimental***
# Comment with # if not used.
i2c:  
  - id: bus_a
    sda: 13
    scl: 14
    scan: true

  - id: bus_b
    sda: 10
    scl: 18
    scan: true

## Option for DHT11 or DHT22 on last 3 terminals -/Signal/+ ***experimental***
## Comment with # if not used.
sensor:
#  - platform: dht
#    model: DHT11
#    pin: 8
#    temperature:
#      name: ${brink_temp_from_inside}
#      id: brink_temp_from_inside
#    humidity:
#      name: ${brink_humidity_from_inside}
#      id: brink_humidity_from_inside
#    update_interval: 15s

## Option for M5stack ENV III temperature, humidity and pressure sensor on i2c bus ***experimental***
#  - platform: sht3xd
#    temperature:
#      name: "Living Room Temperature ENVIII"
#    humidity:
#      name: "Living Room Humidity ENVIII"
#    i2c_id: bus_a
#    address: 0x44
#    update_interval: 60s

#  - platform: qmp6988
#    temperature:
#      name: "Living Room Temperature2 ENVIII"
#      oversampling: 16x
#    pressure:
#      name: "Living Room Pressure ENVIII"
#      oversampling: 16x
#    i2c_id: bus_a
#    address: 0x70
#    update_interval: 60s
#    iir_filter: 2x

## Option for M5stack SCD41, CO2, humidity and temperature sensor on i2c bus ***experimental***
  - platform: scd4x
    co2:
     name: ${brink_co2_from_inside}
     id: brink_co2_from_inside
    humidity:
      name: ${brink_humidity_from_inside}
      id: brink_humidity_from_inside
    temperature:
      name: ${brink_temp_from_inside}
      id: brink_temp_from_inside
#    temperature_offset: "2.0°C"
    i2c_id: bus_b
    address: 0x62
    update_interval: 60s

## Option for Relay  ***experimental***
## Comment with # if not used.
switch:
  ## Relay
  - platform: gpio
    pin:
      number: 5
      inverted: false
    name: "Relay"
    id: brink_relay
#    internal: true
    icon: mdi:alarm-bell

# Enable/Disable logging
logger:
  logs:
#    modbus_controller.sensor: WARN
#    modbus_controller.output: WARN
#    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    dht.sensor: WARN
    switch: WARN
    button: WARN
    number: WARN
  # baud_rate: 0  # <--- super important! for ESP8266

wifi:
  ap:
    ssid: "${name} hotspot"
    password: "configesp"

captive_portal:

# Enable Web server.
web_server:
  port: 80

# Enable Status LED.
status_led:
  pin:
    number: 17