### ESP32 used is a MH-ET-LIVE, also known as Wemos D32 Mini 
### The modbus TTL to RS485 interface used is a XY-017  (RS3485). No flow control needed and 3.3V powersupply
esp8266:
  board: nodemcuv2

uart:
  id: mod_bus
  tx_pin: D2
  rx_pin: D1
  baud_rate: 19200
  stop_bits: 1
  parity: even

# Enable/Disable logging
logger:
  baud_rate: 0  # <--- super important! for ESP8266
