## Based on a Flair 400, to changes max values for Flair 300 change all max_value in lines 725 - 774 to 325
substitutions:
  name: brink
  friendly_name: Brink
  device_description: "Esphome component for Brink Flair with modbus"
  timezone: "Europe/Amsterdam"

# In order to use other language or a different ESP chip, fix include file name below:
# Currently supported languages are en, nl. 
# ESP32 is a mh-et-live or wemos d32 mini, esp8266 is a wemos d1 mini, esp32s3 is a lilygo ESP32S3-T7
# Be carefull not to upload the wrong code to the wrong chip. This could brick your ESP chip.

# for developing/testing, uncomment local includes and comment out remote_package part.
# <<: !include boards/board-esp32S3.yaml

packages:
  remote_package:
    url: https://github.com/fonske/Brink-flair-modbus
    files: 
      - esphome/labels/.brink-labels-en.yaml
      # - esphome/labels/.brink-labels-nl.yaml
      # - esphome/boards/board-esp32.yaml
      - esphome/boards/board-esp32S3.yaml
      # - esphome/boards/board-esp8266.yaml
      # - esphome/sensors/sensor-scd41-i2c-dfrobot.yaml
      # - esphome/sensors/sensor-scd41-i2c-m5stack.yaml
      # - esphome/sensors/sensor-enviii-i2c-m5stack.yaml
      # - esphome/sensors/sensor-dht22.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Put your API key here if you have one
# api:
#   encryption:
#     key: !secret brink_api_key
