## i2c for DFROBOT GRAVITY SCD41, CO2 sensor - remove if not used
i2c:  
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
## extra DHT22 sensor on the house suction side as it is not present in the Brink Flair.
#  - platform: dht
#    model: DHT22
#    pin: 22
#    temperature:
#      name: Binnen aanzuig temperatuur
#      id: temp_from_inside
#    humidity:
#      name: Binnen aanzuig luchtvochtigheid
#      id: humidity_from_inside
#    update_interval: 15s

  ## extra SCD41 sensor on the house suction side as it is not present in the Brink Flair. Remove if not used
  - platform: scd4x
    co2:
      name: ${${lang}_co2_from_inside}
      id: co2_from_inside
      on_value:
        then:
        - if:
            condition:
              lambda: 'return x < 1000;'
            then:
            else:
            - if:
                condition:
                  lambda: 'return x > 1500;'
                then:
                else:
        
    humidity:
      name: ${${lang}_humidity_from_inside}
      id: humidity_from_inside
      on_value:
        then:
        - if:
            condition:
              lambda: 'return x < 30;'
            then:
            else:
            - if:
                condition:
                  lambda: 'return x > 60;'
                then:
                else:

    temperature:
      name: ${${lang}_temp_from_inside}
      id: temp_from_inside

    temperature_offset: "2.0°C"
    
  - id: performance
    name: Rendement
    platform: template
    unit_of_measurement: "%"
    update_interval: 30s
    lambda: 'return ((id(temp_to_inside).state - id(temp_from_outside).state)/(id(temp_from_inside).state - id(temp_from_outside).state)*100);'
   # (temp_to_inside - temp_from_outside) / (temp_from_inside - temp_from_outside)
   