name: Build ESPHome firmware

# Controls when the action will run. Triggers the workflow on push
on: 
  push:
  pull_request:
  release:
        
jobs:
  build:
    runs-on: ubuntu-latest 
    name: "Build"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Patch config to test on esp8266"
        run: |
          # awk  '/^[ -]+esphome\/(boards|sensors|.brink)/ {sub("esphome", "device_base"++count":& ")} 1' esphome/brink.yaml 
          sed -i '/remote_package:/,+15d' esphome/brink.yaml
          sed -i '/^packages:/a\ \ substitutions: !include labels/.brink-labels-en.yaml\n\ \ device_base: !include .brink.base.yaml\n\ \ device_base2: !include boards/board-esp8266.yaml' esphome/brink.yaml
      - name: "Build esp8266"
        uses: esphome/build-action@v1.8.0
        id: esphome-build-esp8266
        with:
          yaml_file: esphome/brink.yaml
      - name: "Patch config to test on esp32"
        run: |
          sed -i '/device_base2:/d' esphome/brink.yaml
          sed -i '/device_base:/a\ \ device_base2: !include boards/board-esp32.yaml' esphome/brink.yaml' esphome/brink.yaml
      - name: "Build esp32"
        uses: esphome/build-action@v1.8.0
        id: esphome-build-esp32
        with:
          yaml_file: esphome/brink.yaml
  