name: Build ESPHome firmware

# Controls when the action will run. Triggers the workflow on push
on: 
  push:
  pull_request:
  release:
        
jobs:
  build:
    runs-on: ubuntu-latest 
    name: "Build"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Extract branch name
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo Branch name: $branch
        id: extract_branch
      - name: "Test on local include files"
        run: |
          sed -i 's#fonske/Brink-flair-modbus#${{ github.repository }}#g' esphome/brink.yaml
      - name: "Build"
        uses: esphome/build-action@v1
        id: esphome-build
        with:
          yaml_file: esphome/brink.yaml
