name: Build ESPHome firmware

# Controls when the action will run. Triggers the workflow on push
on: 
  push:
  pull_request:
  release:
        
jobs:
  build:
    runs-on: ubuntu-latest 
    name: "Build"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Test on local include files"
        run: |
          sed -i 's/fonske\/Brink-flair-modbus/${{ github.repository }}/g' esphome/brink.yaml
          sed -i 's/ref: main/# ref: ${{github.sha}}/g' esphome/brink.yaml
      - name: "Build"
        uses: esphome/build-action@v1
        id: esphome-build
        with:
          yaml_file: esphome/brink.yaml
